package io.github.xxfast.cupboard.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * One OS chrome palette in one mode, transcribed from design/platform-theme.js
 * (the canonical token table).
 *
 * Every field is non-null: where an OS palette lacks a token, the closest
 * neighbour fills in (tonal=segOn, tonalText=segOnText, outline=border,
 * ctrlB/ctrlBB=border). Gradient tokens (bar, btnGrad, knob) become top/bottom
 * pairs, equal colors where the source is flat.
 */
data class ChromeTokens(
    val barTop: Color,
    val barBottom: Color,
    val barBorder: Color,
    val title: Color,
    val icon: Color,
    val label: Color,
    val hov: Color,
    val hov2: Color,
    val insBg: Color,
    val div: Color,
    val text: Color,
    val subtle: Color,
    val subtle2: Color,
    val ctrl: Color,
    val ctrlText: Color,
    val ctrlHov: Color,
    val ctrlB: Color,
    val ctrlBB: Color,
    val outline: Color,
    val segBg: Color,
    val segOn: Color,
    val segOnText: Color,
    val segOff: Color,
    val track: Color,
    val rowBg: Color,
    val rowHov: Color,
    val badgeOff: Color,
    val badgeOffText: Color,
    val btnTop: Color,
    val btnBottom: Color,
    val knobTop: Color,
    val knobBottom: Color,
    val tonal: Color,
    val tonalText: Color,
    val chrome: Color,
    val panel: Color,
    val border: Color,
    val dim: Color,
    val faint: Color,
    val well: Color,
    val accent: Color,
    val accentText: Color,
)

/** One OS's chrome: both modes plus the palette-independent metrics. */
data class ChromeTheme(
    val dark: ChromeTokens,
    val light: ChromeTokens,
    val winR: Dp,
    val thumbR: Dp,
    val uiLabel: String,
)

val MacChrome: ChromeTheme = ChromeTheme(
    dark = ChromeTokens(
        barTop = Color(0xFF323236),
        barBottom = Color(0xFF2C2C30),
        barBorder = Color(0xFF1A1A1C),
        title = Color(0xFFD8D8DC),
        icon = Color(0xFFD0D0D5),
        label = Color(0xFFB8B8BE),
        hov = Color(1f, 1f, 1f, 0.07f),
        hov2 = Color(1f, 1f, 1f, 0.14f),
        insBg = Color(0xFF29292D),
        div = Color(0xFF3A3A3E),
        text = Color(0xFFE8E8EA),
        subtle = Color(0xFF98989F),
        subtle2 = Color(0xFF85858C),
        ctrl = Color(0xFF414147),
        ctrlText = Color(0xFFECECEE),
        ctrlHov = Color(0xFF55555C),
        ctrlB = Color(0xFF3A3A3E),
        ctrlBB = Color(0xFF3A3A3E),
        outline = Color(0xFF3A3A3E),
        segBg = Color(0xFF313136),
        segOn = Color(0xFF5C5C64),
        segOnText = Color(0xFFFFFFFF),
        segOff = Color(0xFFC8C8CC),
        track = Color(0xFF4A4A50),
        rowBg = Color(0xFF333338),
        rowHov = Color(0xFF3C3C42),
        badgeOff = Color(0xFF4A4A50),
        badgeOffText = Color(0xFFD8D8DC),
        btnTop = Color(0xFF525259),
        btnBottom = Color(0xFF47474D),
        knobTop = Color(0xFFFFFFFF),
        knobBottom = Color(0xFFE8E8E8),
        tonal = Color(0xFF5C5C64),
        tonalText = Color(0xFFFFFFFF),
        chrome = Color(0xFF2C2C30),
        panel = Color(0xFF28282C),
        border = Color(0xFF3A3A3E),
        dim = Color(0xFFA0A0A8),
        faint = Color(0xFF6E6E76),
        well = Color(0xFF17181C),
        accent = Color(0xFF7F52FF),
        accentText = Color(0xFFFFFFFF),
    ),
    light = ChromeTokens(
        barTop = Color(0xFFF6F5F3),
        barBottom = Color(0xFFEAE9E7),
        barBorder = Color(0xFFC8C7C5),
        title = Color(0xFF3A3A3C),
        icon = Color(0xFF4A4A4C),
        label = Color(0xFF5C5C5E),
        hov = Color(0f, 0f, 0f, 0.06f),
        hov2 = Color(0f, 0f, 0f, 0.1f),
        insBg = Color(0xFFEFEEEC),
        div = Color(0xFFD8D7D5),
        text = Color(0xFF2A2A2C),
        subtle = Color(0xFF7A7A7E),
        subtle2 = Color(0xFF94949A),
        ctrl = Color(0xFFFFFFFF),
        ctrlText = Color(0xFF2A2A2C),
        ctrlHov = Color(0xFFE9E9E9),
        ctrlB = Color(0xFFD6D5D3),
        ctrlBB = Color(0xFFD6D5D3),
        outline = Color(0xFFD6D5D3),
        segBg = Color(0xFFE1E0DE),
        segOn = Color(0xFFFFFFFF),
        segOnText = Color(0xFF1D1D1F),
        segOff = Color(0xFF5A5A5C),
        track = Color(0xFFCFCECC),
        rowBg = Color(0xFFE7E6E4),
        rowHov = Color(0xFFDEDEDD),
        badgeOff = Color(0xFFC9C8C6),
        badgeOffText = Color(0xFF3A3A3C),
        btnTop = Color(0xFFFFFFFF),
        btnBottom = Color(0xFFF1F1F1),
        knobTop = Color(0xFFFFFFFF),
        knobBottom = Color(0xFFECECEC),
        tonal = Color(0xFFFFFFFF),
        tonalText = Color(0xFF1D1D1F),
        chrome = Color(0xFFECECEA),
        panel = Color(0xFFF1F0EE),
        border = Color(0xFFD6D5D3),
        dim = Color(0xFF6A6A6E),
        faint = Color(0xFF9A9A9E),
        well = Color(0xFFDCDCDA),
        accent = Color(0xFF7F52FF),
        accentText = Color(0xFFFFFFFF),
    ),
    winR = 19.dp,
    thumbR = 5.dp,
    uiLabel = "ui: SwiftUI / AppKit",
)

val WindowsChrome: ChromeTheme = ChromeTheme(
    dark = ChromeTokens(
        barTop = Color(0xFF202020),
        barBottom = Color(0xFF202020),
        barBorder = Color(0xFF383838),
        title = Color(0xFFFFFFFF),
        icon = Color(0xFFFFFFFF),
        label = Color(0xFFFFFFFF),
        hov = Color(0xFF2D2D2D),
        hov2 = Color(0xFF323232),
        insBg = Color(0xFF272727),
        div = Color(0xFF383838),
        text = Color(0xFFFFFFFF),
        subtle = Color(0xFF9D9D9D),
        subtle2 = Color(0xFF717171),
        ctrl = Color(0xFF2D2D2D),
        ctrlText = Color(0xFFFFFFFF),
        ctrlHov = Color(0xFF383838),
        ctrlB = Color(0xFF383838),
        ctrlBB = Color(0xFF4D4D4D),
        outline = Color(0xFF383838),
        segBg = Color(0xFF2D2D2D),
        segOn = Color(0xFF8961FF),
        segOnText = Color(0xFFFFFFFF),
        segOff = Color(0xFF9D9D9D),
        track = Color(0xFF454545),
        rowBg = Color(0xFF2D2D2D),
        rowHov = Color(0xFF323232),
        badgeOff = Color(0xFF454545),
        badgeOffText = Color(0xFFFFFFFF),
        btnTop = Color(0xFF2D2D2D),
        btnBottom = Color(0xFF2D2D2D),
        knobTop = Color(0xFFFFFFFF),
        knobBottom = Color(0xFFFFFFFF),
        tonal = Color(0xFF8961FF),
        tonalText = Color(0xFFFFFFFF),
        chrome = Color(0xFF202020),
        panel = Color(0xFF272727),
        border = Color(0xFF383838),
        dim = Color(0xFF9D9D9D),
        faint = Color(0xFF717171),
        well = Color(0xFF191919),
        accent = Color(0xFF8961FF),
        accentText = Color(0xFFFFFFFF),
    ),
    light = ChromeTokens(
        barTop = Color(0xFFF3F3F3),
        barBottom = Color(0xFFF3F3F3),
        barBorder = Color(0xFFE0E0E0),
        title = Color(0xFF1A1A1A),
        icon = Color(0xFF1A1A1A),
        label = Color(0xFF1A1A1A),
        hov = Color(0xFFE9E9E9),
        hov2 = Color(0xFFE0E0E0),
        insBg = Color(0xFFF9F9F9),
        div = Color(0xFFE5E5E5),
        text = Color(0xFF1A1A1A),
        subtle = Color(0xFF5F5F5F),
        subtle2 = Color(0xFF8A8A8A),
        ctrl = Color(0xFFFBFBFB),
        ctrlText = Color(0xFF1A1A1A),
        ctrlHov = Color(0xFFF0F0F0),
        ctrlB = Color(0xFFE5E5E5),
        ctrlBB = Color(0xFFCFCFCF),
        outline = Color(0xFFE0E0E0),
        segBg = Color(0xFFECECEC),
        segOn = Color(0xFF6F42E0),
        segOnText = Color(0xFFFFFFFF),
        segOff = Color(0xFF5F5F5F),
        track = Color(0xFFC8C8C8),
        rowBg = Color(0xFFF3F3F3),
        rowHov = Color(0xFFEBEBEB),
        badgeOff = Color(0xFFD8D8D8),
        badgeOffText = Color(0xFF1A1A1A),
        btnTop = Color(0xFFFBFBFB),
        btnBottom = Color(0xFFFBFBFB),
        knobTop = Color(0xFFFFFFFF),
        knobBottom = Color(0xFFFFFFFF),
        tonal = Color(0xFF6F42E0),
        tonalText = Color(0xFFFFFFFF),
        chrome = Color(0xFFF3F3F3),
        panel = Color(0xFFF9F9F9),
        border = Color(0xFFE0E0E0),
        dim = Color(0xFF5F5F5F),
        faint = Color(0xFF8A8A8A),
        well = Color(0xFFEBEBEB),
        accent = Color(0xFF6F42E0),
        accentText = Color(0xFFFFFFFF),
    ),
    winR = 8.dp,
    thumbR = 4.dp,
    uiLabel = "ui: WinUI 3 · Mica",
)

val LinuxChrome: ChromeTheme = ChromeTheme(
    dark = ChromeTokens(
        barTop = Color(0xFF211F26),
        barBottom = Color(0xFF211F26),
        barBorder = Color(0xFF47444F),
        title = Color(0xFFE6E0E9),
        icon = Color(0xFFCBC4D5),
        label = Color(0xFFCBC4D5),
        hov = Color(0xFF38353F),
        hov2 = Color(0xFF413E4A),
        insBg = Color(0xFF211F26),
        div = Color(0xFF47444F),
        text = Color(0xFFE6E0E9),
        subtle = Color(0xFFA29DAA),
        subtle2 = Color(0xFF88838F),
        ctrl = Color(0xFF2B2930),
        ctrlText = Color(0xFFE6E0E9),
        ctrlHov = Color(0xFF38353F),
        ctrlB = Color(0xFF47444F),
        ctrlBB = Color(0xFF47444F),
        outline = Color(0xFF938F99),
        segBg = Color(0xFF2B2930),
        segOn = Color(0xFF4F378B),
        segOnText = Color(0xFFE8DDFF),
        segOff = Color(0xFFCBC4D5),
        track = Color(0xFF4A4458),
        rowBg = Color(0xFF2B2930),
        rowHov = Color(0xFF38353F),
        badgeOff = Color(0xFF47444F),
        badgeOffText = Color(0xFFE6E0E9),
        btnTop = Color(0xFF2B2930),
        btnBottom = Color(0xFF2B2930),
        knobTop = Color(0xFFD0BCFF),
        knobBottom = Color(0xFFD0BCFF),
        tonal = Color(0xFF4A4458),
        tonalText = Color(0xFFE8DDFF),
        chrome = Color(0xFF211F26),
        panel = Color(0xFF1C1B1F),
        border = Color(0xFF47444F),
        dim = Color(0xFFA29DAA),
        faint = Color(0xFF736F7A),
        well = Color(0xFF141317),
        accent = Color(0xFFD0BCFF),
        accentText = Color(0xFF381E72),
    ),
    light = ChromeTokens(
        barTop = Color(0xFFF3EDF7),
        barBottom = Color(0xFFF3EDF7),
        barBorder = Color(0xFFCAC4D0),
        title = Color(0xFF1D1B20),
        icon = Color(0xFF49454F),
        label = Color(0xFF49454F),
        hov = Color(0f, 0f, 0f, 0.06f),
        hov2 = Color(0f, 0f, 0f, 0.1f),
        insBg = Color(0xFFF3EDF7),
        div = Color(0xFFCAC4D0),
        text = Color(0xFF1D1B20),
        subtle = Color(0xFF79747E),
        subtle2 = Color(0xFF938F99),
        ctrl = Color(0xFFFFFFFF),
        ctrlText = Color(0xFF1D1B20),
        ctrlHov = Color(0xFFE8E2EC),
        ctrlB = Color(0xFFCAC4D0),
        ctrlBB = Color(0xFFCAC4D0),
        outline = Color(0xFF79747E),
        segBg = Color(0xFFECE6F0),
        segOn = Color(0xFFE8DEF8),
        segOnText = Color(0xFF1D192B),
        segOff = Color(0xFF49454F),
        track = Color(0xFFE6E0E9),
        rowBg = Color(0xFFECE6F0),
        rowHov = Color(0xFFE2DCE8),
        badgeOff = Color(0xFFCAC4D0),
        badgeOffText = Color(0xFF1D1B20),
        btnTop = Color(0xFFFFFFFF),
        btnBottom = Color(0xFFFFFFFF),
        knobTop = Color(0xFF6750A4),
        knobBottom = Color(0xFF6750A4),
        tonal = Color(0xFFE8DEF8),
        tonalText = Color(0xFF1D192B),
        chrome = Color(0xFFF3EDF7),
        panel = Color(0xFFFEF7FF),
        border = Color(0xFFCAC4D0),
        dim = Color(0xFF49454F),
        faint = Color(0xFF79747E),
        well = Color(0xFFE3DDEA),
        accent = Color(0xFF6750A4),
        accentText = Color(0xFFFFFFFF),
    ),
    winR = 16.dp,
    thumbR = 10.dp,
    uiLabel = "ui: Compose Desktop · M3",
)

/** The resolved palette of the chrome currently drawing, Linux dark by default. */
val LocalChromeTokens: ProvidableCompositionLocal<ChromeTokens> =
    staticCompositionLocalOf { LinuxChrome.dark }

/**
 * The tokens as an M3 [ColorScheme], so stock Material components (menus, tabs,
 * ripples) pick up the chrome palette without per-call color plumbing.
 */
fun ChromeTokens.toColorScheme(dark: Boolean): ColorScheme {
    val base: ColorScheme = if (dark) darkColorScheme() else lightColorScheme()

    return base.copy(
        primary = accent,
        onPrimary = accentText,
        secondaryContainer = tonal,
        onSecondaryContainer = tonalText,
        surface = panel,
        background = chrome,
        surfaceVariant = ctrl,
        outline = outline,
        onSurface = text,
        onSurfaceVariant = dim,
    )
}
